### ISSUE TITLE
Problemas con pgAdmin para consultar base de datos

### ISSUE THREAD

**Issue by jparedes-marnagarage** [bluemixmg/Ideation-Toolchain#4]
![image](https://cloud.githubusercontent.com/assets/25669802/23033530/cbc64dfe-f44e-11e6-8647-7355adc6eb57.png)
Es la primera vez que trato de conectarme a la base de datos actualmente en uso desde mi computadora.
@bluemixmg @bgutierrez600

**Comment by bgutierrez600** [comment]
Julio, por favor informame si instalando la version que descargaste se te soluciono el problema. 

@jparedes-marnagarage

**Comment by jparedes-marnagarage** [comment]
Sí, @bgutierrez600, pero consumía mucha RAM y decidí quedarme usando la consola.
